language: python
env:
  global:
  - secure: U6PO13Ek4WGWqkx1g9nearxLiK9QEOp0/YcncDGtK1uTjH4poEfL4+Zdqdmusgz0ZPzEbpNdDjrVkPdzlHfMCLiD7b1F0ZXwZn8gZaQRljCFVN4gRxHHUSDuhqMCfByJe2dAai7G+NP7k2c4j+kjMMNt0L8Sg9kxPjk99ZH0EL4=
  - secure: SPjDIc4Qs4FsnCUyHbsYKj8+7FmltTrFfoRBEqbYvSC6onRjfkauJEFSBkO2sTv/usa5AcKmCBjfMiqSya2/eSjJzti7d1AWHrtIe8CsU4/KtJkCT/3Y72HJk35CRpUyp/Pd3dhASjrAvI7aByU60EvRfxcwtNJEumwx0bM+OE8=
  - BOB_UPLOAD_WHEEL=1
matrix:
  include:
  - python: 2.6
  - python: 2.7
    env:
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
  - python: 3.3
  - python: 3.4
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install --force-yes libboost-all-dev libblitz1-dev libhdf5-serial-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- pip install --upgrade --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel numpy scipy sphinx nose matplotlib coverage cpp-coveralls
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel -r requirements.txt --pre coveralls
install:
- python bootstrap-buildout.py
- CPPFLAGS=--coverage LDFLAGS=--coverage ./bin/buildout buildout:debug=false buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
script:
- ./bin/python -c 'import pkg_resources; from bob.measure import get_config; print(get_config())'
- ./bin/coverage run --source=bob.measure ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- cpp-coveralls --build-root=`pwd` --exclude=src --exclude-pattern=".*Compiler.*" --dump=cpp_cov.json
- coveralls --merge=cpp_cov.json
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
- ./upload-sphinx.sh
- ./upload-wheel.sh
